### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris-extras#4]
Documentation should include an illustration of how Agg is utilised to allow the raster approach to work.

**Comment by pelson** [comment]
Incidentally, ```scitools.github.io/iris-extras``` can be achieved by having a gh-pages branch in this repo (I believe).

**Comment by rhattersley** [comment]
Or there's http://readthedocs.org/

**Comment by cpelley** [comment]
Perhaps this is not the right place to ask this but what's the advantages over http://readthedocs.org/ over the github gh-pages approach?  I have used gh-pages and found it to be great.  I'm guessing the readthedocs approach could be updated as part of the travis build which might be an advantage??
I think biggus is hosted via readthedocs right?
