### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by rhattersley** [SciTools/iris-extras#7]
re: #1, #5, and #6

cc @bjlittle, @niallrobinson, @cpelley, and @pelson

The `iris-extras` repo has got the ball rolling for "non-core Iris functionality" which is great. Now that we've got some real examples we can take the next step in figuring out how to structure/manage it all. Our options are (please suggest other options as appropriate, I can add them to the list):
1. One repo, `iris-extras`, with a single `setup.py`. All projects installed, versioned, and released together.
2. One repo, `iris-extras`, with a directory for each "project". Each directory contains its own `setup.py`. Projects installed independently but versioning and releases unclear.
3. A repo for each group of related project, e.g. `iris-regrid`. Groups of projects installed, versioned, and released independently, but within a group all projects are managed together.
4. A repo for each project, e.g. `iris-agg-regrid`. Each project is installed, versioned, and released independently.

NB. To some extent we can combine options, e.g. things start in (1) but then progress to (4) at some point. Perhaps projects become independent if they require dependencies that aren't already mandatory for Iris.

**Comment by rhattersley** [comment]
FWIW, at the moment I'm leaning towards options (3) and (4). And if I had to decide *right now* I'd go for (4).

**Comment by cpelley** [comment]
I agree, though I have preference for option (3).  Option (4) does not have strong negative implications for workflow/releases.  Potentially there is not much difference in workflow and deployment between (3) and (4) though for those who visit the github SciTools, (3) might reduce the 'repository namespace' compared to (4) which is a plus.

(2) could work... but I think there is more to document in terms of workflow and structure (1) would have the undesirable (unnecessary) dependencies between project releases.  This could offer problem for 'projects' which are dependent on time critical releases.

**Comment by cpelley** [comment]
Thanks for opening this issue @rhattersley 
Certainly an exciting opportunity.

**Comment by rhattersley** [comment]
> (3) might reduce the 'repository namespace' compared to (4) which is a plus

Another way to manage the namespace would be to create a SciTools-incubator organisation (e.g. see https://github.com/Jupyter-incubator). Then it matters less whether we do (3) or (4). If/when things migrate from SciTools-incubator to SciTools we have more of an idea how to [un]group things appropriately.

**Comment by cpelley** [comment]
> Another way to manage the namespace would be to create a SciTools-incubator organisation...

Oh interesting, yeah that sounds fine.  How would you suggest we get to a decision on this?  You suggestion is the least controversial to Scitools so perhaps that is simply the way to move forwards, at least for now?

cc @jkettleb

**Comment by rhattersley** [comment]
> How would you suggest we get to a decision on this?

[Do it](https://github.com/SciTools-incubator) and ask forgiveness afterwards. :wink:

**Comment by pelson** [comment]
Option 3 👍
